import asyncio
import json
import logging
import os
import re
import uuid
from typing import Any, Dict, List, Optional

import google.generativeai as genai
from datetime import datetime
from dotenv import load_dotenv
from flask import Flask, jsonify, request
from pydantic import BaseModel, Field
from supabase import Client, create_client

from error_email_sender import send_error_email

load_dotenv() 

# --- CONFIGURATION ---
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("GodsEye-SOV")

# Initialize Clients
try:
    if not SUPABASE_URL or not SUPABASE_KEY or not GEMINI_API_KEY:
        raise ValueError("Missing API Keys in environment variables.")
    
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    genai.configure(api_key=GEMINI_API_KEY)
except Exception as e:
    logger.error(f"Initialization Failed: {e}")
    raise e

# --- DATA MODELS ---

class SingleQueryInsight(BaseModel):
    original_analysis_id: str = Field(description="The UUID of the source row being analyzed")
    query_text: str = Field(description="The search query text")
    sov_score: int = Field(description="0-99 score. Practical and strict scoring based on visibility.")
    category_relevance: str = Field(description="High, Medium, or Low relevance. Is the AI discussing the exact problem/category this product solves?")
    citation_status: str = Field(description="Cited (Link), Mentioned (Text only), or None")
    winning_entity: str = Field(description="The brand/domain that owns the most 'Real Estate' in the answer")
    reasoning: str = Field(description="One sentence explaining the score based on visibility and dominance.")

class BatchAnalysisResult(BaseModel):
    insights: List[SingleQueryInsight]
    batch_summary: str = Field(description="Summary of this batch's performance.")

# --- CORE LOGIC ---

class SOVAnalyzer:
    def __init__(self, product_profile: Dict, engine: str = 'google', debug_mode: bool = False):
        self.product_profile = product_profile
        self.product_name = product_profile.get('product_name', 'Unknown Product')
        self.engine = engine  # 'google' or 'perplexity'
        self.debug_mode = debug_mode
        self.model = genai.GenerativeModel('gemini-2.5-pro') 

    def _log_debug(self, message: str, data: Any = None):
        if self.debug_mode:
            print(f"\n[DEBUG] {message}")
            if data:
                print(json.dumps(data, indent=2, default=str))
            print("-" * 40)

    def _clean_json_text(self, text: str) -> str:
        """Strips markdown code blocks to prevent parsing errors."""
        cleaned = text.strip()
        if cleaned.startswith("```"):
            cleaned = re.sub(r"^```[a-zA-Z]*\n", "", cleaned)
        if cleaned.endswith("```"):
            cleaned = re.sub(r"\n```$", "", cleaned)
        return cleaned.strip()

    async def _analyze_chunk(self, chunk_data: List[Dict]) -> BatchAnalysisResult:
        if self.debug_mode:
            self._log_debug(f"Sending Batch of {len(chunk_data)} queries to Gemini...")

        engine_context = ""
        if self.engine == 'perplexity':
            engine_context = "For Perplexity AI, look for the main generated answer text and the citation numbers (e.g., [1], [2]) usually linked to sources."
        else:
            engine_context = "For Google AI Overview, look for the 'ai_overview', 'summary', or 'answer_box' text."

        prod_context = f"""
        **Product Name:** {self.product_name}
        **Description:** {self.product_profile.get('description', 'N/A')}
        **Problem Solved:** {self.product_profile.get('problem_product_is_solving', 'N/A')}
        **Target Market:** {self.product_profile.get('targeted_market', 'N/A')}
        **Product Type:** {self.product_profile.get('specific_product_type', 'N/A')}
        """

        prompt = f"""
        You are an AEO (Answer Engine Optimization) Strategist.
        
        **Target Product Profile:**
        {prod_context}
        
        **Target Engine:** {self.engine.upper()}
        
        **Objective:** Calculate **Share of Voice (SOV)** and **Category Opportunity (Relevance)**.
        
        **Instructions:**
        I have provided a list of {len(chunk_data)} items. Each contains a query and the raw JSON of the {self.engine} response.
        {engine_context}
        
        For EACH item:
        1. **Locate the Answer:** Find the main text summary generated by the AI.
        
        2. **Analyze Presence (SOV) - STRICT SCORING:**
           - **0 (Absent):** Not found at all.
           - **1-30 (Weak):** Passing mention, footer note, or listed very low.
           - **31-60 (Visible):** In a list, middle of the pack, text mention without link.
           - **61-95 (Dominant):** Top 3 position, bolded text, direct citation link.
           - **NOTE:** Never give 100. Max is 99. Be strict.

        3. **Analyze Category Relevance:** Even if the product is absent, is the AI discussing the *exact problem* or *category* this product solves?
           - **High:** The answer lists competitors or solutions for the exact problem defined in the Product Profile. (This is a missed opportunity).
           - **Medium:** The answer is related but broad (e.g., general marketing tips vs specific tool).
           - **Low:** The answer is irrelevant to what this product does.

        4. **Identify Winner:** Which brand/domain has the highest "Share of Real Estate"?
        
        **Input Data:**
        {json.dumps(chunk_data)}
        """

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    response_mime_type="application/json",
                    response_schema=BatchAnalysisResult
                )
            )
            
            clean_text = self._clean_json_text(response.text)
            result = BatchAnalysisResult.parse_raw(clean_text)

            # --- PROGRAMMATIC CLAMP (The "No 100%" Guarantee) ---
            for insight in result.insights:
                # Force cap SOV at 99
                if insight.sov_score >= 100:
                    insight.sov_score = 99
            # ----------------------------------------------------

            return result
        except Exception as e:
            logger.error(f"Gemini Batch Analysis Failed: {e}")
            if self.debug_mode:
                print(f"[ERROR DEBUG] Response Text that failed: {response.text}")
            return BatchAnalysisResult(insights=[], batch_summary="Batch failed.")

    async def _merge_and_narrate(self, new_insights: List[SingleQueryInsight], batch_summaries: List[str], old_snapshot: Optional[Dict]) -> Dict:
        new_count = len(new_insights)
        
        if new_count > 0:
            sum_sov = sum(i.sov_score for i in new_insights)
            sum_citation = sum(1 for i in new_insights if i.citation_status == 'Cited')
            
            # --- RELEVANCE MATH FIX (No 100s allowed) ---
            sum_relevance = 0
            for i in new_insights:
                rel_clean = i.category_relevance.strip().lower()
                # Changed from 100 to 95 to ensure "Practical Numbers"
                if rel_clean == 'high': sum_relevance += 95  
                elif rel_clean == 'medium': sum_relevance += 50
                # Low remains 0
            # --------------------------------------------
        else:
            sum_sov = 0
            sum_citation = 0
            sum_relevance = 0
        
        old_count = old_snapshot.get('total_queries_analyzed', 0) if old_snapshot else 0
        old_sov = float(old_snapshot.get('global_sov_score', 0)) if old_snapshot else 0.0
        old_citation = float(old_snapshot.get('citation_score', 0)) if old_snapshot else 0.0
        
        old_relevance = float(old_snapshot.get('category_relevance', 0) or old_snapshot.get('sentiment_score', 0)) if old_snapshot else 0.0
        
        total_count = old_count + new_count
        
        if total_count > 0:
            final_sov = round(((old_sov * old_count) + sum_sov) / total_count)
            final_citation = round(((old_citation * old_count) + (sum_citation / new_count * 100 if new_count else 0) * new_count) / total_count) if new_count or old_count else 0
            final_relevance = round(((old_relevance * old_count) + sum_relevance) / total_count)
        else:
            final_sov = 0
            final_citation = 0
            final_relevance = 0

        # Double check final safety clamp
        if final_sov >= 100: final_sov = 99
        if final_relevance >= 100: final_relevance = 99

        trend_direction = "First Analysis"
        if old_count > 0:
            diff = final_sov - old_sov
            if diff > 2: trend_direction = "Improving"
            elif diff < -2: trend_direction = "Declining"
            else: trend_direction = "Stable"

        final_prompt = f"""
        You are a Senior AEO Analyst providing a strategic summary for the client "{self.product_name}".
        
        **Current Status:**
        - Engine: {self.engine.upper()}
        - Brand Visibility (SOV): {final_sov}/100 (Trend: {trend_direction})
        - Category Opportunity (Relevance): {final_relevance}/100
        - Citation Trust: {final_citation}%
        
        **Instructions:**
        1. **Do NOT output a list of stats.** Do NOT say "Visibility is X and Relevance is Y". The client can see the numbers.
        2. **Explain the meaning.** Connect the dots between Visibility and Relevance.
        3. **Specific Scenario Handling:**
           - IF Visibility is LOW (<20) but Relevance is HIGH (>70): You MUST write: "The AI is actively discussing your exact solution category, but currently ignoring your brand in favor of competitors. This is a high-value missed opportunity."
           - IF Visibility is HIGH: Focus on how dominant the brand is.
        
        **Format:** Write 2-3 clear, professional sentences explaining the situation.
        """
        
        try:
            narrative_resp = self.model.generate_content(final_prompt)
            narrative = narrative_resp.text
        except:
            narrative = f"Visibility: {final_sov}%. Trust: {final_citation}%. Category Relevance: {final_relevance}%."

        return {
            "global_sov": final_sov,
            "citation_score": final_citation,
            "category_relevance": final_relevance,
            "total_queries": total_count,
            "narrative": narrative,
            "insights": new_insights
        }

    async def process_product(self, product_id: str) -> Dict[str, Any]:
        try:
            logger.info(f"🚀 Starting {self.engine.upper()} Analysis for Product ID: {product_id}")
            
            p_res = supabase.table("products").select("*").eq("id", product_id).execute()
            if not p_res.data:
                return {"success": False, "error": f"Product ID {product_id} not found."}
            
            product_data = p_res.data[0]
            self.product_profile = product_data
            self.product_name = product_data.get('product_name')
            
            existing_res = supabase.table("sov_query_insights")\
                .select("analysis_id")\
                .eq("product_id", product_id)\
                .eq("engine", self.engine)\
                .execute()
                
            analyzed_ids = {row['analysis_id'] for row in existing_res.data}
            
            if self.debug_mode:
                self._log_debug(f"Found {len(analyzed_ids)} previously analyzed {self.engine} queries.")

            if self.engine == 'perplexity':
                source_table = "product_analysis_perplexity"
                query_column = "optimization_prompt"
            else:
                source_table = "product_analysis_google"
                query_column = "search_query"
            
            raw_res = supabase.table(source_table)\
                .select(f"id, {query_column}, raw_serp_results")\
                .eq("product_id", product_id)\
                .execute()
            
            new_rows = []
            for row in raw_res.data:
                if row['id'] not in analyzed_ids:
                    query_text = row.get(query_column) or "Unknown Query"
                    new_rows.append({
                        "id": row['id'],
                        "search_query": query_text,
                        "raw_serp_results": row['raw_serp_results']
                    })
            
            if not new_rows:
                logger.info(f"No new {self.engine} queries to analyze.")
                return {"success": True, "message": f"Data is up to date for {self.engine}."}

            BATCH_SIZE = 15
            batches = []
            for i in range(0, len(new_rows), BATCH_SIZE):
                chunk = new_rows[i:i + BATCH_SIZE]
                formatted_chunk = []
                for row in chunk:
                    formatted_chunk.append({
                        "original_analysis_id": row['id'],
                        "query": row['search_query'],
                        "raw_serp_data": row['raw_serp_results'] 
                    })
                batches.append(formatted_chunk)

            all_new_insights = []
            batch_summaries = []
            
            for idx, batch in enumerate(batches):
                logger.info(f"Analyzing Batch {idx+1}/{len(batches)}...")
                result = await self._analyze_chunk(batch)
                
                if not result.insights:
                    logger.warning(f"Batch {idx+1} returned 0 insights. Check Gemini parsing.")
                
                all_new_insights.extend(result.insights)
                if result.batch_summary:
                    batch_summaries.append(result.batch_summary)

            snap_res = supabase.table("sov_product_snapshots")\
                .select("*")\
                .eq("product_id", product_id)\
                .eq("engine", self.engine)\
                .order("created_at", desc=True)\
                .limit(1)\
                .execute()
            old_snapshot = snap_res.data[0] if snap_res.data else None

            final_output = await self._merge_and_narrate(all_new_insights, batch_summaries, old_snapshot)

            try:
                batch_uuid = str(uuid.uuid4())
                snap_payload = {
                    "product_id": product_id,
                    "global_sov_score": final_output['global_sov'],
                    "citation_score": final_output['citation_score'],   
                    "category_relevance": final_output['category_relevance'], 
                    "total_queries_analyzed": final_output['total_queries'],
                    "narrative_summary": final_output['narrative'],
                    "batch_id": batch_uuid,
                    "engine": self.engine,
                    "analyzed_at": "now()" 
                }
                supabase.table("sov_product_snapshots").insert(snap_payload).execute()

                insights_payload = []
                for insight in final_output['insights']:
                    insights_payload.append({
                        "analysis_id": insight.original_analysis_id,
                        "product_id": product_id,
                        "sov_score": insight.sov_score,
                        "category_relevance": insight.category_relevance, 
                        "citation_status": insight.citation_status,
                        "winning_source": insight.winning_entity, 
                        "ai_narrative": insight.reasoning,
                        "engine": self.engine 
                    })
                
                if insights_payload:
                    chunk_size = 50
                    for i in range(0, len(insights_payload), chunk_size):
                        chunk = insights_payload[i:i+chunk_size]
                        supabase.table("sov_query_insights").insert(chunk).execute()
                    logger.info(f"✅ Successfully saved {len(insights_payload)} insights.")
                else:
                    logger.warning("⚠️ Snapshot saved, but NO individual query insights were generated.")

            except Exception as e:
                logger.error(f"DB Save Failed: {e}")
                send_error_email(error=e, error_context=f"Database save failed for product_id={product_id}, engine={self.engine}", api_key=GEMINI_API_KEY)
                return {"success": False, "error": str(e)}

            return {
                "success": True,
                "data": {
                    "engine": self.engine,
                    "global_score": final_output['global_sov'],
                    "citation_score": final_output['citation_score'],
                    "category_relevance": final_output['category_relevance'],
                    "narrative": final_output['narrative']
                }
            }
        
        except Exception as e:
            logger.error(f"Critical Error in process_product: {e}")
            send_error_email(error=e, error_context=f"Critical failure in process_product for product_id={product_id}, engine={self.engine}", api_key=GEMINI_API_KEY)
            return {"success": False, "error": str(e)}

# --- SERVERLESS HANDLER ---
app = Flask(__name__)

# Add this before the if __name__ == "__main__": block
@app.route('/health', methods=['GET'])
def health_check():
    """Lightweight endpoint to keep serverless container warm"""
    return jsonify({
        "status": "healthy",
        "service": "GodsEye-SOV",
        "timestamp": datetime.utcnow().isoformat()
    }), 200

@app.route('/analyze', methods=['POST'])
def handle_analyze():
    try:
        data = request.json
        if not data or 'product_id' not in data:
            return jsonify({"error": "Missing product_id"}), 400
        
        product_id = data['product_id']
        engine = data.get('engine', 'google') 
        debug = data.get('debug', False)
        
        if engine not in ['google', 'perplexity']:
            return jsonify({"error": "Invalid engine. Use 'google' or 'perplexity'"}), 400

        analyzer = SOVAnalyzer(product_profile={}, engine=engine, debug_mode=debug)
        result = asyncio.run(analyzer.process_product(product_id))
        return jsonify(result)
        
    except Exception as e:
        logger.error(f"Handler Error: {e}")
        send_error_email(error=e, error_context="Crash in /analyze route", api_key=GEMINI_API_KEY)
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"🚀 SOV Backend Running (Development Mode) on port {port}")
    app.run(debug=True, host='0.0.0.0', port=port)
