import asyncio
import json
import logging
import os
import uuid
from typing import Any, Dict, List, Optional

import google.generativeai as genai
from dotenv import load_dotenv
from flask import Flask, jsonify, request
from pydantic import BaseModel, Field
from supabase import Client, create_client

from error_email_sender import send_error_email

load_dotenv() 

# --- CONFIGURATION ---
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("GodsEye-SOV")

# Initialize Clients
try:
    if not SUPABASE_URL or not SUPABASE_KEY or not GEMINI_API_KEY:
        raise ValueError("Missing API Keys in environment variables.")
    
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
    genai.configure(api_key=GEMINI_API_KEY)
except Exception as e:
    logger.error(f"Initialization Failed: {e}")
    raise e

# --- DATA MODELS ---

class SingleQueryInsight(BaseModel):
    original_analysis_id: str = Field(description="The UUID of the source row being analyzed")
    query_text: str = Field(description="The search query text")
    sov_score: int = Field(description="0-100 score. 100=Dominant (Primary Answer), 50=Visible (List/Mention), 0=Absent")
    sentiment: str = Field(description="Positive, Neutral, or Negative")
    citation_status: str = Field(description="Cited (Link), Mentioned (Text only), or None")
    winning_entity: str = Field(description="The brand/domain that owns the most 'Real Estate' in the answer")
    reasoning: str = Field(description="One sentence explaining the score based on visibility and dominance.")

class BatchAnalysisResult(BaseModel):
    insights: List[SingleQueryInsight]
    batch_summary: str = Field(description="Summary of this batch's performance.")

# --- CORE LOGIC ---

class SOVAnalyzer:
    def __init__(self, product_name: str, engine: str = 'google', debug_mode: bool = False):
        self.product_name = product_name
        self.engine = engine  # 'google' or 'perplexity'
        self.debug_mode = debug_mode
        # Use stable model version
        self.model = genai.GenerativeModel('gemini-2.5-pro') 

    def _log_debug(self, message: str, data: Any = None):
        """Helper to print verbose logs only when debug_mode is True"""
        if self.debug_mode:
            print(f"\n[DEBUG] {message}")
            if data:
                print(json.dumps(data, indent=2, default=str))
            print("-" * 40)

    async def _analyze_chunk(self, chunk_data: List[Dict]) -> BatchAnalysisResult:
        """
        Sends a count-limited batch (max 15) of FULL RAW JSON data to Gemini.
        """
        if self.debug_mode:
            self._log_debug(f"Sending Batch of {len(chunk_data)} queries to Gemini...")

        # Adjusted instructions for Perplexity vs Google
        engine_context = ""
        if self.engine == 'perplexity':
            engine_context = "For Perplexity AI, look for the main generated answer text and the citation numbers (e.g., [1], [2]) usually linked to sources."
        else:
            engine_context = "For Google AI Overview, look for the 'ai_overview', 'summary', or 'answer_box' text."

        prompt = f"""
        You are an AEO (Answer Engine Optimization) Strategist.
        
        **Target Product:** "{self.product_name}"
        **Target Engine:** {self.engine.upper()}
        
        **Objective:** Calculate the **Share of Voice (SOV)** for the target product.
        
        **Instructions:**
        I have provided a list of {len(chunk_data)} items. Each contains a query and the raw JSON of the {self.engine} response.
        {engine_context}
        
        For EACH item:
        1. **Locate the Answer:** Find the main text summary generated by the AI.
        2. **Analyze Presence:** Is "{self.product_name}" mentioned?
        3. **Calculate Matrices:**
           - **Citation:** Is there a clickable link or footnote citation?
           - **Sentiment:** How is the brand described?
           - **Real Estate:** Does the brand occupy the main answer?
        
        4. **Assign Score (0-100):**
           - **100 (Dominant):** The product IS the answer. It takes up the majority of the text or is the #1 recommendation.
           - **75 (Strong):** Listed in the top 3 options with a direct citation.
           - **50 (Visible):** Mentioned in a list of 5+ items, or mentioned without a link.
           - **25 (Weak):** A passing mention, a footer note, or negative sentiment.
           - **0 (Absent):** Not found.

        5. **Identify Winner:** Which brand/domain has the highest "Share of Real Estate"?
        
        **Input Data:**
        {json.dumps(chunk_data)}
        """

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    response_mime_type="application/json",
                    response_schema=BatchAnalysisResult
                )
            )
            
            result = BatchAnalysisResult.parse_raw(response.text)
            return result
        except Exception as e:
            logger.error(f"Gemini Batch Analysis Failed: {e}")
            return BatchAnalysisResult(insights=[], batch_summary="Batch failed.")

    async def _merge_and_narrate(self, new_insights: List[SingleQueryInsight], batch_summaries: List[str], old_snapshot: Optional[Dict]) -> Dict:
        # 1. Stats for the NEW Batch
        new_count = len(new_insights)
        
        # Calculate Averages for the NEW batch
        if new_count > 0:
            sum_sov = sum(i.sov_score for i in new_insights)
            # Count citations: 1 if 'Cited', 0 otherwise
            sum_citation = sum(1 for i in new_insights if i.citation_status == 'Cited')
            # Calculate Sentiment Score: Positive=100, Neutral=50, Negative=0
            sum_sentiment = 0
            for i in new_insights:
                if i.sentiment == 'Positive': sum_sentiment += 100
                elif i.sentiment == 'Neutral': sum_sentiment += 50
                # Negative is 0
        else:
            sum_sov = 0
            sum_citation = 0
            sum_sentiment = 0
        
        # 2. Stats for the OLD Data
        old_count = old_snapshot.get('total_queries_analyzed', 0) if old_snapshot else 0
        old_sov = float(old_snapshot.get('global_sov_score', 0)) if old_snapshot else 0.0
        old_citation = float(old_snapshot.get('citation_score', 0)) if old_snapshot else 0.0
        old_sentiment = float(old_snapshot.get('sentiment_score', 0)) if old_snapshot else 0.0
        
        # 3. Weighted Averages (The "Rolling" Math)
        total_count = old_count + new_count
        
        if total_count > 0:
            final_sov = round(((old_sov * old_count) + sum_sov) / total_count)
            # Citation Score is a % (0-100)
            final_citation = round(((old_citation * old_count) + (sum_citation / new_count * 100 if new_count else 0) * new_count) / total_count) if new_count or old_count else 0
            # Sentiment is already 0-100 scale
            final_sentiment = round(((old_sentiment * old_count) + sum_sentiment) / total_count)
        else:
            final_sov = 0
            final_citation = 0
            final_sentiment = 0

        # 4. Narrative
        trend_direction = "First Analysis"
        if old_count > 0:
            diff = final_sov - old_sov
            if diff > 2: trend_direction = "Improving"
            elif diff < -2: trend_direction = "Declining"
            else: trend_direction = "Stable"

        # Updated Prompt to include all 3 metrics
        final_prompt = f"""
        Write a 2-sentence Dashboard Summary for "{self.product_name}" on {self.engine.upper()}.
        
        **Data Context:**
        - **Visibility (SOV):** {final_sov}/100 (Trend: {trend_direction})
        - **Trust (Citation Rate):** {final_citation}% of answers link to us.
        - **Reputation (Sentiment):** {final_sentiment}/100.
        - Recent Insights: {" ".join(batch_summaries)}
        
        **Task:** Summarize the brand's AI performance, mentioning not just visibility but also trust/sentiment if notable.
        """
        
        try:
            narrative_resp = self.model.generate_content(final_prompt)
            narrative = narrative_resp.text
        except:
            narrative = f"Visibility: {final_sov}%. Trust: {final_citation}%. Reputation: {final_sentiment}%."

        return {
            "global_sov": final_sov,
            "citation_score": final_citation,
            "sentiment_score": final_sentiment,
            "total_queries": total_count,
            "narrative": narrative,
            "insights": new_insights
        }

    async def process_product(self, product_id: str) -> Dict[str, Any]:
        try:
            logger.info(f"🚀 Starting {self.engine.upper()} Analysis for Product ID: {product_id}")
            
            # 1. Fetch Product Name
            p_res = supabase.table("products").select("product_name").eq("id", product_id).execute()
            if not p_res.data:
                return {"success": False, "error": f"Product ID {product_id} not found."}
            self.product_name = p_res.data[0]['product_name']
            
            # 2. DELTA LOGIC (Filtered by Engine)
            existing_res = supabase.table("sov_query_insights")\
                .select("analysis_id")\
                .eq("product_id", product_id)\
                .eq("engine", self.engine)\
                .execute()
                
            analyzed_ids = {row['analysis_id'] for row in existing_res.data}
            
            if self.debug_mode:
                self._log_debug(f"Found {len(analyzed_ids)} previously analyzed {self.engine} queries.")

            # 3. FETCH RAW DATA (FIXED LOGIC HERE)
            # Determine the table and the specific query column name based on engine
            if self.engine == 'perplexity':
                source_table = "product_analysis_perplexity"
                query_column = "optimization_prompt"
            else:
                source_table = "product_analysis_google"
                query_column = "search_query"
            
            # Select dynamically
            raw_res = supabase.table(source_table)\
                .select(f"id, {query_column}, raw_serp_results")\
                .eq("product_id", product_id)\
                .execute()
            
            new_rows = []
            for row in raw_res.data:
                if row['id'] not in analyzed_ids:
                    # Normalize the query text using the dynamic column name
                    query_text = row.get(query_column) or "Unknown Query"
                    
                    new_rows.append({
                        "id": row['id'],
                        "search_query": query_text,
                        "raw_serp_results": row['raw_serp_results']
                    })
            
            if not new_rows:
                logger.info(f"No new {self.engine} queries to analyze.")
                return {"success": True, "message": f"Data is up to date for {self.engine}."}

            if self.debug_mode:
                self._log_debug(f"Identified {len(new_rows)} NEW {self.engine} queries to analyze.")

            # 4. BATCHING LOGIC
            BATCH_SIZE = 15
            batches = []
            for i in range(0, len(new_rows), BATCH_SIZE):
                chunk = new_rows[i:i + BATCH_SIZE]
                formatted_chunk = []
                for row in chunk:
                    formatted_chunk.append({
                        "original_analysis_id": row['id'],
                        "query": row['search_query'],
                        "raw_serp_data": row['raw_serp_results'] 
                    })
                batches.append(formatted_chunk)

            # 5. EXECUTION
            all_new_insights = []
            batch_summaries = []
            
            for idx, batch in enumerate(batches):
                logger.info(f"Analyzing Batch {idx+1}/{len(batches)}...")
                result = await self._analyze_chunk(batch)
                all_new_insights.extend(result.insights)
                if result.batch_summary:
                    batch_summaries.append(result.batch_summary)

            # 6. HISTORY FETCH (Filtered by Engine)
            snap_res = supabase.table("sov_product_snapshots")\
                .select("*")\
                .eq("product_id", product_id)\
                .eq("engine", self.engine)\
                .order("created_at", desc=True)\
                .limit(1)\
                .execute()
            old_snapshot = snap_res.data[0] if snap_res.data else None

            # 7. MERGE
            final_output = await self._merge_and_narrate(all_new_insights, batch_summaries, old_snapshot)

            # 8. SAVE TO DB
            try:
                # A. Save Snapshot
                batch_uuid = str(uuid.uuid4())
                snap_payload = {
                    "product_id": product_id,
                    "global_sov_score": final_output['global_sov'],
                    "citation_score": final_output['citation_score'],   
                    "sentiment_score": final_output['sentiment_score'], 
                    "total_queries_analyzed": final_output['total_queries'],
                    "narrative_summary": final_output['narrative'],
                    "batch_id": batch_uuid,
                    "engine": self.engine,
                    "analyzed_at": "now()" 
                }
                supabase.table("sov_product_snapshots").insert(snap_payload).execute()

                # B. Save Query Insights
                insights_payload = []
                for insight in final_output['insights']:
                    insights_payload.append({
                        "analysis_id": insight.original_analysis_id,
                        "product_id": product_id,
                        "sov_score": insight.sov_score,
                        "sentiment": insight.sentiment,
                        "citation_status": insight.citation_status,
                        "winning_source": insight.winning_entity, 
                        "ai_narrative": insight.reasoning,
                        "engine": self.engine 
                    })
                
                if insights_payload:
                    chunk_size = 50
                    for i in range(0, len(insights_payload), chunk_size):
                        chunk = insights_payload[i:i+chunk_size]
                        supabase.table("sov_query_insights").insert(chunk).execute()

                logger.info("✅ Analysis saved successfully.")

            except Exception as e:
                logger.error(f"DB Save Failed: {e}")
                # Trigger email alert for database save failure
                send_error_email(error=e, error_context=f"Database save failed for product_id={product_id}, engine={self.engine}", api_key=GEMINI_API_KEY)
                return {"success": False, "error": str(e)}

            return {
                "success": True,
                "data": {
                    "engine": self.engine,
                    "global_score": final_output['global_sov'],
                    "citation_score": final_output['citation_score'],
                    "sentiment_score": final_output['sentiment_score'],
                    "narrative": final_output['narrative']
                }
            }
        
        except Exception as e:
            logger.error(f"Critical Error in process_product: {e}")
            # Trigger email alert for critical failure
            send_error_email(error=e, error_context=f"Critical failure in process_product for product_id={product_id}, engine={self.engine}", api_key=GEMINI_API_KEY)
            return {"success": False, "error": str(e)}

# --- SERVERLESS HANDLER ---
app = Flask(__name__)

@app.route('/analyze', methods=['POST'])
def handle_analyze():
    try:
        data = request.json
        if not data or 'product_id' not in data:
            return jsonify({"error": "Missing product_id"}), 400
        
        product_id = data['product_id']
        engine = data.get('engine', 'google') # Default to google if not provided
        debug = data.get('debug', False)
        
        if engine not in ['google', 'perplexity']:
            return jsonify({"error": "Invalid engine. Use 'google' or 'perplexity'"}), 400

        analyzer = SOVAnalyzer(product_name="Unknown", engine=engine, debug_mode=debug)
        result = asyncio.run(analyzer.process_product(product_id))
        return jsonify(result)
        
    except Exception as e:
        logger.error(f"Handler Error: {e}")
        # Trigger AI-powered error email
        send_error_email(error=e, error_context="Crash in /analyze route", api_key=GEMINI_API_KEY)
        return jsonify({"error": str(e)}), 500

# This block only runs if you explicitly type 'python sov_backend_3_google_and_perplexity.py'
# It will NOT run when deployed to Gunicorn/Vercel/AWS Lambda
# For production, use: gunicorn sov_backend_3_google_and_perplexity:app
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"🚀 SOV Backend Running (Development Mode) on port {port}")
    app.run(debug=True, host='0.0.0.0', port=port)